### PR TITLE
fix: update to "headers-polyfill@3.1"

### LINKED ISSUE #285: Package subpath './lib' is not defined by "exports"
I just ran `npm update`, which updated `headers-polyfill` to the just released `3.1.0`, which modifies the exports in `package.json`. This is the error I get:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib' is not defined by "exports" in /myapp/node_modules/headers-polyfill/package.json
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:464:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:748:3)
    at resolveExports (node:internal/modules/cjs/loader:493:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:533:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:942:27)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/myapp/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/NodeClientRequest.js:89:13) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

Issue is `import { Headers, objectToHeaders } from 'headers-polyfill/lib'` in `NodeClientRequest.ts` ([here](https://github.com/mswjs/interceptors/blob/94458729283528fe8977ccfdf04257ec5ea4f053/src/interceptors/ClientRequest/NodeClientRequest.ts#L5)), as `lib` is not exposed any more.

Guess the fix is
```diff
- import { Headers, objectToHeaders } from 'headers-polyfill/lib'
+ import { Headers, objectToHeaders } from 'headers-polyfill'
```

### PR DESCRIPTION
**Pull request by kettanaito**
Fixes a regression introduced by https://github.com/mswjs/headers-polyfill/pull/38.

- Fixes #285

No longer import `headers-polyfill/lib`. Instead, import `headers-polyfill` (root).

### CODE REVIEW

**Comment by kettanaito** [comment]
Experiencing a bunch of failing installation attempts from the Yarn registry. Looks like the registry's issue.

**Review by jordevo — APPROVED** [review]

**Comment by kettanaito** [comment]
Marking this as `fix` as we're not making any breaking changes to the public API. Migrating to a dependency that now supports ESM may be problematic but we're not dropping CommonJS.

**Comment by kettanaito** [comment]
Thanks for a swift review, @jordevo! 🎉 Let's wait for the Yarn/NPM registry to be up before merging this.

**Review by kikoruiz — APPROVED** [review]

**Comment by kettanaito** [comment]
## Released: v0.17.5 🎉

This has been released in v0.17.5!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.17.5)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.17.5)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Pull request merged**
