### PR TITLE
Emits the "request" event in the ClientRequest and XMLHttpRequest overrides

### PR DESCRIPTION
**Pull request by nravic**
Fix for https://github.com/mswjs/interceptors/issues/111.

### CODE REVIEW

**Comment by chaoyangnz** [comment]
nice to be fixed.

**Comment by chaoyangnz** [comment]
question? I don't think `request` event is really useful, when it has `Resolver` which even can get the raw http.Request

**Comment by kettanaito** [comment]
@chaoyangnz, it's a good point. I suppose the difference is mainly semantic: `resolver` is meant to return a mocked response (even if conditionally). The "request" event is a ready-only way to find out that a request has happened. Anyway, this is a good point to refine at v1.0

**Review by kettanaito — APPROVED** [review]
Thank you for fixing this, @nravic! I've added a test suite that asserts the "request" event being properly emitted. 

Welcome to contributors!

**Comment by nravic** [comment]
Sounds good, thank you!

**Comment by nravic** [comment]
@kettanaito do you have an estimate of when you'll publish the npm package with the changes so I can use it? 

Thank you again!

**Comment by kettanaito** [comment]
@nravic, I'll publish it on the weekend. Meanwhile, you can still react to requests in the `resolver` argument of `createInterceptors()` function.

**Pull request merged**
