### PR TITLE
fix(xhr): clone the request before calculating its body size

### LINKED ISSUE #630: XHR is broken in 0.34.3
It seems that a regression was introduced into the XMLHttpRequestController in the 0.34.3 release.

I have not yet been able to identify the root cause, but here is a [codesandbox](https://codesandbox.io/p/devbox/5xl3y2?file=/src/index.spec.ts:48,1-56,1) showing a test passing with `window.fetch()` and failing with `axios.put()`. The XHR request simply never returns and results in a timeout.

### PR DESCRIPTION
**Pull request by robbtraister**
- Fixes #630

The root cause of the issue is that cloning the Request to calculate the `Content-Length` header occurs too late. At the point in which clone() is called, the body buffer has already been consumed, so cloning fails.

Since this `kFetchRequest` value is only used for this specific purpose of calculating content-length, there is no harm in creating and storing a clone immediately upon creation of the Request object.

### CODE REVIEW

**Comment by ddolcimascolo** [comment]
Hey all, can we get this merged and msw released?

Thx,
David

**Comment by robbtraister** [comment]
@kettanaito I tried adding a test, but I can't seem to duplicate the behavior. In the test environment, reading the request buffer does not seem to lock it from future attempts to read/clone.

This is a simplification of what I tried:
```js
  interceptor.once('request', async ({ controller, request }) => {
    await request.arrayBuffer() // <-- this is the addition to the existing test, along with changing to POST
    controller.respondWith(
      new UndiciResponse('Hello world') as unknown as Response
    )
  })
```

**Comment by ddolcimascolo** [comment]
@robbtraister I'm impacted by this one and I'm using Vite + Vitest. Please see https://github.com/mswjs/msw/issues/2273#issuecomment-2340935025

**Comment by kettanaito** [comment]
> I was able to figure out a hacky workaround by importing Request from "undici" and setting it to global.Request in the beforeAll hook, then reverting in the afterAll hook. Does that seem reasonable?

Hmm, this seems a bit too much. We _are_ using the Undici's `Request`. Let me take a look at what we can do to improve these tests, and how to drive out this problematic scenario.

**Comment by kettanaito** [comment]
I've added an isolated test and confirm it failing with the following error without the proposed fix:

```
TypeError: unusable
 ❯ Request.clone ../node:internal/deps/undici/undici:7289:17
 ❯ XMLHttpRequestController.respondWith ../src/interceptors/XMLHttpRequest/XMLHttpRequestController.ts:299:29
    297|     if (this[kFetchRequest]) {
    298|       const totalRequestBodyLength = await getBodyByteLength(
    299|         this[kFetchRequest].clone()
       |                             ^
    300|       )
    301| 
 ❯ Object.onResponse ../src/interceptors/XMLHttpRequest/XMLHttpRequestProxy.ts:70:24
 ❯ handleResponse ../src/utils/handleRequest.ts:55:21
 ❯ Module.handleRequest ../src/utils/handleRequest.ts:207:12
 ❯ processTicksAndRejections ../node:internal/process/task_queues:95:5
 ❯ XMLHttpRequestController.xhrRequestController.onRequest ../src/interceptors/XMLHttpRequest/XMLHttpRequestProxy.ts:64:34
```

With the fix, the test is passing.

**Review by kettanaito — APPROVED** [review]
This looks great. Waiting for the tests before merging.

**Comment by robbtraister** [comment]
It looks like the key difference is using the `jsdom` environment in lieu of `happy-dom`. Either way, thanks for getting it working.

**Comment by kettanaito** [comment]
## Released: v0.35.3 🎉

This has been released in v0.35.3!

- 📄 [**Release notes**](https://github.com/mswjs/interceptors/releases/tag/v0.35.3)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/interceptors/v/0.35.3)

Make sure to always update to the latest version (`npm i @mswjs/interceptors@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Pull request merged**
