### PR TITLE
fix(fetch): do not optimistically rely on "location" in fetch interceptor

### PR DESCRIPTION
**Pull request by till**
- Related: mswjs/msw#1555

### CODE REVIEW

**Review by kettanaito — COMMENTED** [review]
Hey, @till! Thanks for making this fix happen. I've added a little change, composing the URL inline. What do you think about it?

**Comment by till** [comment]
@kettanaito works for me. I tend to reach for boring or more verbose solutions, so I probably wouldn't do it like that, but your code/project/rules. 👍👍👍

**Review by kettanaito — APPROVED** [review]

**Comment by kettanaito** [comment]
Thanks for fixing this, @till! Welcome to contributors. I will release this change from that intermediate branch today.

**Comment by till** [comment]
Thanks for your help!

**Pull request merged**
